# DATA_DIR = "input/captcha_images_v2/"
# DATA_DIR ="/home/arslan/reCaptcha Clusters/Large_Captcha_Dataset"
DATA_DIR = "/home/arslan/reCaptcha Clusters/100x36"
BATCH_SIZE = 8
IMAGE_WIDTH = 300
IMAGE_HEIGHT = 75
NUM_WORKERS = 8
EPOCHS = 150
DEVICE = "cuda"
